### ISSUE TITLE
Please consider using ynh_install_php

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/kimai2_ynh#13]
Hi

We noticed that you use an another version of php than the current version of stretch. Installing another version of php can (will probably) breaks YunoHost for other apps.
Please consider using the experimental helper [ynh_install_php](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_install_php/ynh_install_php) to handle securely other version of php.

If you encounter any problem using this helper, please open an issue on the repo.

**Comment by jodumont** [comment]
Related to this
I believe Kimai mess with php such as declare here
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/211

For an obscur reason

I was unable to install nextcloud because php-zip was missing (even if it is declare in the common file)

2019-06-15 07:37:10,952: DEBUG - PHP module zip not installed.
2019-06-15 07:37:10,952: WARNING - Unable to install Nextcloud
I was able to fix this by installing php7.0-zip

on my system php-zip refered to php7.3-zip
which is refered in /etc/apt/sources.list.d/php7.list
which based on date was declared by kimai2
